import type { Metadata } from "next";
import { Cormorant_Garamond,
  Lato,
  Allura } from "next/font/google";
import "./globals.css";

const cormorant = Cormorant_Garamond({
  variable: "--font-c",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});
const lato = Lato({
  variable: "--font-l",
  weight: ["300", "400", "700"],
  subsets: ["latin"],
  display: "swap",
});
const allura = Allura({
  variable: "--font-a",
  weight: "400",
  subsets: ["latin"],
  display: "swap"
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`
      ${cormorant.variable}
      ${lato.variable}
      ${allura.variable}
      h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
